### ISSUE TITLE
Invariat violation:element type is invalid, expected string but got undefined

### ISSUE THREAD

**Issue by mir1198yusuf** [bamlab/react-native-image-header-scroll-view-example#10]
Could not import properly

```
import HeaderImageScrollView, { TriggeringView } from 'react-native-image-header-scroll-view';

return (
    <HeaderImageScrollView
      maxHeight={200}
      minHeight={100}
      renderForeground={() => (
        <View style={{ height: 150, justifyContent: "center", alignItems: "center" }} >
            <Text style={{ backgroundColor: "transparent" }}>Tap Me!</Text>
        </View>
      )}
    >
      <View style={{ height: 1000 }}>
        <TriggeringView onHide={() => console.log("text hidden")}>
          <Text>Scroll Me!</Text>
        </TriggeringView>
      </View>
    </HeaderImageScrollView>
  );
```

**Comment by Chandravardhan8998** [comment]
Same Problem

**Comment by mir1198yusuf** [comment]
This is a mistake in npm website documentation.

So see the GitHub page documentation. 
https://github.com/bamlab/react-native-image-header-scroll-view

It is ImageHeaderScrollView (as on GitHub page ) and not HeaderImageScrollView (as on npm page)

So this problem is solved , now another problem the latest version of library doesnot trigger scrolling events as in this issue https://github.com/bamlab/react-native-image-header-scroll-view/issues/92

So use older version of library.
see this two comment for solution.
https://github.com/bamlab/react-native-image-header-scroll-view/issues/92#issuecomment-774402394
 https://github.com/bamlab/react-native-image-header-scroll-view/issues/92#issuecomment-774402689

Now it should work fine.

**Comment by mir1198yusuf** [comment]
Closing issue as problem is solved by using older version.

Solution is the two links mentioned at bottom in previous comment.
